name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y nasm
    - name: Clean
      run: make clean
    - name: Compile
      run: make
    - name: Install test dependencies
      run: |
        sudo apt-get install -y bats bats-assert bats-support
        mkdir -p tests/test_helper
        ln -s /usr/lib/bats/bats-support tests/test_helper/bats-support
        ln -s /usr/lib/bats/bats-assert tests/test_helper/bats-assert
    - name: Test
      run: make test
